/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_floodlightcontroller_DPIAPP_REJNI */

#ifndef _Included_net_floodlightcontroller_DPIAPP_REJNI
#define _Included_net_floodlightcontroller_DPIAPP_REJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_floodlightcontroller_DPIAPP_REJNI
 * Method:    Match
 * Signature: (Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_floodlightcontroller_DPIAPP_REJNI_Match
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
